### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by bluesherpa** [devcontainers/templates#146]
Is there a working example of a project that uses the CPP template?

The following workflow would be really helpful:

- Open Visual Studio Code
- Press F1
- Select Dev Containers: New Dev Container
- Enter a project name
- Select Create Dev Container
- Select Run > Start Debugging

The application would compile, run, and display "Hello World!".

The result would be:

- A Docker image that includes everything needed for basic C++ development and can be easily extended to add more libraries or tools as needed.
- Code that you can execute and also step through for debugging.
- Integration with the IDE for IntelliSense.
- Git support.
- Use of a Docker Volume for increased I/O performance.

Bonus points for including a description of the workflow for checking out the code, making changes to it, running and stepping through the code, and then saving changes back into Git.

Thanks in advance for any example you have or help creating something like this. I'm happy to create a Pull Request to add if that helps.

-Ed

**Comment by samruddhikhandale** [comment]
Hi 👋 

Have you looked at [microsoft/vscode-remote-try-cpp](https://github.com/microsoft/vscode-remote-try-cpp)? that's a sample app for CPP. Wondering if that would be helpful.

**Comment by samruddhikhandale** [comment]
We have various repositories in https://github.com/devcontainers for different purposes, it would be nice if you would be able to identify (whether the issue is with the CLI/images/Features or something else) and open an issue accordingly.

If your question is more generic, then feel free to post it in https://github.com/orgs/devcontainers/discussions.
We also have a community slack channel, if you're interested in joining, please look at https://github.com/orgs/devcontainers/discussions/3

**Comment by bluesherpa** [comment]
Thanks again, this ticket can be closed.
