### ISSUE TITLE
Req: Dev Containers rebuild Postgres container

### ISSUE THREAD

**Issue by duffney** [devcontainers/templates#193]
It doesn't seem possible to be able to use the Dev Container: Rebuild Container action to reset the database container. Which leaves going into Docker and deleting the db container from there. Also worth mentioning that the db volume should be deleted in the rebuild. :)

**Comment by samruddhikhandale** [comment]
Hi 👋 

> Dev Container: Rebuild Container 

Thanks for raising this issue, looks like it is tied to the `Dev Containers` extension rather than the Template itself? 

Can you help open an issue in https://github.com/microsoft/vscode-remote-release/issues, the VS Code team should be able to help address this problem. Thank you! 

// cc @bamurtaugh

**Comment by duffney** [comment]
@samruddhikhandale thank you for the reply. That makes total sense I'll open a different issue over there and close this one. Thanks!
